sudo: false
language: scala
jdk:
  - oraclejdk11

scala_version_212: &scala_version_212 "2.12.10"
scala_version_213: &scala_version_213 "2.13.1"

before_install:
  - git fetch --tags
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    - stage: test
      name: test 2.12
      script: sbt ++$TRAVIS_SCALA_VERSION test
      scala: *scala_version_212
    - stage: test
      name: test 2.13
      script: sbt ++$TRAVIS_SCALA_VERSION test
      scala: *scala_version_213
    - stage: release
      name: release
      script: sbt ci-release
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.sbt"
before_cache:
  - find $HOME/.sbt -name "*.lock" -print -delete
env:
  global:
  - secure: OAO9Ni0hAj6+H8KJLue84aaJpMYPAAkm1ox6M4PDjotYc9bQ0u1jtGE8frH9oAahoZsmbKT+hB5UxWfQnFczguUVwrTXOJfsnbD10W0RhlQc+NhwSHiW4Tpz24AKr2j/rZg5KK3CWmEit0MLtBa6MuC78yrSOfGE4RfKr8NdC0GuT93UrYcU2ns1kCg9aTUWGtYUGm4gmpkqJKssf731aYskdNTpTJ1YJNBY+kGnORdRp07gLXL96UByQIQH76v5BQIO0VthqiXioIW4t/ZdLih9n/d21amgxoMKhuAjWDuwGTlQPz3Dw3mHRAeyg11SMEzbyC332fLSsXhab+JmlAI9eyU4p7rKE92Bb2r8MXt/xANTrVQ15BOmTnZ76raGox/lO+Fc4y0ZriE2YcGDGm66OjWVZRR82z3rZZgOXWBuYAGv4GeQUTarFL5lcH30QPooPvxIvcPhohTcpEhgmjFuuvl+fwp1uD+WDn1TET6KmKI3P8phgq9whCIxGwOxQoDeEAE93ekQC2YUeXok+4bT27O2W8evkO/auiYTKmiZGDEjbwZPblPZDudyBhAQ8UIgydhg66WK8FuRuKUNB+5Sx0JhHLCLWKMumxr9LJ2qWHhcqu0NcIcy5t3YIxEhGcYehf9tPeb5ENIMdd41XBcAEeJwXGLPABUDDnrg6xk=
  - secure: of1KihD9GoTuZTYC9LawScez6XPdEVPeZ1a1xadOb4Jo6jTbacnPo1qj6tGECT6skjlC3mWS3V/tECMBw3EEnta79ovV0Kk08SOmEdMGHDlty0qXPrTqNwlAFP2OJtStyVsVGom1luUs2OBhsRw80TWpCaWogo5zXutWyh2zT6/+2kNiLbYk5gzCYw2sVGPzrJ4pTfk7pWW3GAhgNeQ1Ko8bTizJBsdm0mYj0/5fRpfZn4GhmD2VmX31SkLIfEzt2jnQ5Y9gvV2Z8CrrVeRZtStrFsZPsOY8tEjmzddJ8ErP0Xfb5qVHcNTCgm6IWztiCMjUCSf61Uvan/2aabO+/1d/EQgqk2+fOfSoCCYi+xDi1gFPIRlKnJfMnU/LfJeayfzeaQh4szZalX95bXoZO21deAbnsUsuXXKtW8a3RQGdMNQ+kk2ujUbrdzllhVN+Ur8hAALHLDAbGLzMnEAuH3EwKVE84lLCxAqn0IDz+eSCzq8Qe45UgqTGMRTFSxphpZ17/DOU7Fi6uw1me+utPD4Zau/2lnQaG/5YJ42UHmgw/WCRPyamLK91JaL+qkK3B3mCYlR8MIi3Fwr3KQ6pmgrKt12x2dMCqKfNu0IjiBsNUNbvWiT71MivpH+2+aXmIC1fnQThCQtSHR+l1sqb50h9hQ1uxtSpzKsG7l3av+E=
  - secure: THlxGuJpBm6mH7YrasLFm1yc/2YAfy2AQT+ACgJW+ixWJI1dmxK0AsZxL+X0oGJEOeypUfbolaLPFxIdWpdy4L8xpqJ/EK+Sp9Y8Sm9v4VdVfcP6z48Qe87kjr2XU8c3kZRNEytOBryWPoR8JMDkmDawwZQ0vkMNvd4iem4pi3GGA47wp5AOCXMjPBbAiM9biFdj1HB+P5Pcfu5vEqLFiCmw4YmHevZIA5wsNPKEScyS78PtKef94TG8mIGK9BzYPZsrcp5bhMJ7lyjib9rE7ung+X8ljD4eLgdNu3XlwjA6PoV0gfvozg6uGMA7ocLD82NDt2CCGW0u7pMyJ0RLY6XMMDPjFgY7V/+3dd0sZYrmXaMjezmrdG79Y3rkBa+81lS3SXphxtQXmT+fkbkheTxC/CjTNXesKBIBtO9IeH9VMPMyvemYobXt/erVkSnWstQTrnzGX5UljakPyPe6YSQHPAS3CXDXX2tH1GokcytIQOB3Bt2HFHBN7zbbJLQfDQhTB48UuurF8SQmEF4OfXzhfmOdYspg9nSqyVZnzcPGnRwyA2bdnAtQ8FeMZarY6dk+Y4j0YrHAqaQafKXyoAz8myZiXk3m97FQYsrOkKIygm/Q6Wjm8/KHJFar9tVgQYSAufav8WqqtuPYSVDHRhlXPAFedrABReH7e5JjvF8=
