sudo: false
language: scala
scala:
- 2.12.6
script:
- sbt ++$TRAVIS_SCALA_VERSION test
jdk:
- oraclejdk8
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_a7802a534f57_key -iv $encrypted_a7802a534f57_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d;
    tar xv -C travis -f travis/secrets.tar;
  fi
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly; fi
env:
  global:
  - secure: aJMx4mnaXlhl/zg23tE6qo+uPpQ7FwwcEJGEns8NC50E5DE+0r8CUoy7YeZfzVuqNS14sjzwz3pOiU9Agt/3qkTT5TodOyk34xBqH7M48SkhujM4gdLfVCD4LIlmLQ59nXlZYLwiD7oP2ZwQIjlWSgs2fgrla54lSOMLfB2rx1NZ5GNXSiMmk26+6ElJzwtUuGh9lFKXSeoEKvaHE1LA1CCwq3aoAf76GaZeyheNwSPkuipEIecLveNkcvuQfNHt6tXy4cnhp8y7SMbqbg5JDFdKitn5DJFWBP7DOS6Knpo5dh3w1tFHrr+AysBt4Rj4BIt+/x1OJ7SPSRSnnIJvUY3uoj6WOH+6pr4ENkmDp1m1ISY8hTxd8O0BXWZTTzF1f5cVVvOS3zwu0l3faIUqtn2swoGDd/hCSWG+orWAAR4eLXGUPNqZQm+GdEeFUBmqAN0Ldu42/JIDp2P46Hs9N726wO6uxp7qPuXi8cSCgJUvz/QHTAhM+BSow/gXAxLoOccvzxSpI5QcI5nR8oDkG+ciLiNqe67Kx+Xl4qaPuvauQZ1reaLgHvQskU6nLnzgQjriSJ/dPOA6pUjYfiSW68pEljmBlZ2eBQDs91yGqdh68JPMZ+0BVtzhMQi1V7b0fkOfOZy4EapdWOxI/NOVcVLVbq00Tc30KKiPTuSVMm8=
  - secure: FKz/w1qZ0isQ6vd2IVabb7Pwj9/TyOCVB6nKuPZTlPDmL9GydK3Asc/p0wAaSHYuY3IsE2iMtmvk2HWXPj7K+q8jE5VCvlFu50F4LhyGGqnzET5po/BKsjWXkeIODTmZTxiN0vG1lW3VShG9edliiiBr8O6w0YvfBvQoVBdYFsXUY2BM1cOvRpL7PzXLf66NyA8AFkbeW0MypsnIbkvzagnSdljnyM/SCmq8DZZlxRYLvppdJ4l5mrW8+RLB1Dbw/fNTsGoxyCds6lsLJ4SFuCNeKY3CXD028wReYGqs4V3GFWqCc4eavBieseZjS09Sua7dnCT9j2gQAKII7KmogUt7SZNV6cMGdh/ZxI3HWCKIPbmJrZRUj9sMs6tK+JHbNJgJvfv6XRHIBaQ5x1H6+NN+4FGMeC2MrSK95RURYKxbn4v+11ksMbZiFhssiKHmOjrb/JicubCzs1VbjQ1RaPtb0nLWb9794VxOCWvgAfWL5DMzdBTgA9raYz7+5H4xnZ6KZj1R/xQtk3Uyx09ngqUw0OKhCVSER+NY96PXfztr1M0fdrZHvYCD7tHYzQ1MpWVxHjBODj0Wm6ObbettqVXX1BJerQ8XSQ9gFGml899EXBAzw3JbtFaFmlcsSjiraDAFjx0qj4VsMw62xWeMtX5Nhw7e73aO6kyXpE+cw68=
  - secure: Y8Md0xuAw+mA/RuxHecSx7DvCiEnnXPZ/uBZWfRmIy4cr4u/n0PxufR2PW19zXVHDj7oZHpK1v9QWZpvXIe/D8dOe9Fz/OzVh15qkB/h1APGNzqwZ2ADVrkmCpfRjKBEI4wtVdTHNDvbmAgytLOZbSkOEQ7CeQdRhTEMKAwoFtMEBQkFSPX4AY5nglVIUIzUT9Z3Oiaq1EcH0FCsEJKj9gUI5jr5e9r1JfY2fmjtQTiuK04ngi+3I35Ib2kPUClYpb/WZywfubO0j6p/SuQHyYqNTCN/Z5Dj+qA6avcoXb07rIpWCdDrzSv6YcMchgsktVxphmXdwI53S7vLk6pnu7mZM7paweTTc7Y77m5IeMu9IZXIPTpUg89BEgA/swEgw9H4HmcOiWjMIxKD3l1r+HOi22fmIhKQcz20vCetTzb0MY9IUpFGnXN367uMHiZXWkAFYlxAIlD4bW5I9fFJJuVslVSre7cKO0zCvAvS1xA0ovjK93zgr8WQ6RAJ3bu/bCJ4N31NeBH5s7gOdjO3R7bPLLxa+RU7U3Z37tcqIcqnvQBURt1KnsZTEs9gy3eMHr0JCXx41aaQ6CyWI5lRauc6ir4/B7dJOA19sHto6GfsnrDsl6wV2xg8NKhgsynhw5Z2UPTh6esbI2PSLQzttaZ92uHKSes2B5tT3wAHT9s=
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
dist: trusty
